services:
  postgres:
    image: postgres:17
    container_name: rai_postgres
    restart: always
    environment:
      POSTGRES_DB: rai_db
      POSTGRES_USER: hw
      POSTGRES_PASSWORD: mypassword
    ports:
      - "35432:5432"
    volumes:
      - rai3_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hw -d rai_db || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  rai3_pg_data:
    driver: local
